{"name": "Demarrage", "status": "failed", "statusDetails": {"message": "Setup failed:\nWebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Could not find a connected Android device in 20071ms.\nStacktrace:\nUnknownError: An unknown server-side error occurred while processing the command. Original error: Could not find a connected Android device in 20071ms.\n    at getResponseForW3CError (C:\\Users\\monsh\\AppData\\Roaming\\npm\\node_modules\\appium\\node_modules\\@appium\\base-driver\\lib\\protocol\\errors.js:1073:9)\n    at asyncHandler (C:\\Users\\monsh\\AppData\\Roaming\\npm\\node_modules\\appium\\node_modules\\@appium\\base-driver\\lib\\protocol\\protocol.js:491:57)\n\nAlso teardown failed:\nNo application is open"}, "start": 1689338731145, "stop": 1689338763646, "uuid": "50fb322e-7f24-4b7c-bd67-9726a75da050", "historyId": "84a88efa2949dbb22117d72f5b94008a", "fullName": "Tests.homeTest.Demarrage", "labels": [{"name": "suite", "value": "Tests"}, {"name": "subSuite", "value": "homeTest"}, {"name": "framework", "value": "robotframework"}, {"name": "language", "value": "cpython3"}, {"name": "host", "value": "LAPTOP-KC6KER4Q"}, {"name": "thread", "value": "default-22cde012-bef5-4fef-bcc7-d0bd5a4daeed"}, {"name": "tag", "value": "test_001"}]}