{"name": "Demarrage", "status": "failed", "statusDetails": {"message": "Setup failed:\nWebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Could not find a connected Android device in 20278ms.\nStacktrace:\nUnknownError: An unknown server-side error occurred while processing the command. Original error: Could not find a connected Android device in 20278ms.\n    at getResponseForW3CError (C:\\Users\\monsh\\AppData\\Roaming\\npm\\node_modules\\appium\\node_modules\\@appium\\base-driver\\lib\\protocol\\errors.js:1073:9)\n    at asyncHandler (C:\\Users\\monsh\\AppData\\Roaming\\npm\\node_modules\\appium\\node_modules\\@appium\\base-driver\\lib\\protocol\\protocol.js:491:57)\n\nAlso teardown failed:\nNo application is open"}, "start": 1689337786881, "stop": 1689337819934, "uuid": "64e38962-54e0-451e-ad2f-9a83481f3479", "historyId": "84a88efa2949dbb22117d72f5b94008a", "fullName": "Tests.homeTest.Demarrage", "labels": [{"name": "suite", "value": "Tests"}, {"name": "subSuite", "value": "homeTest"}, {"name": "framework", "value": "robotframework"}, {"name": "language", "value": "cpython3"}, {"name": "host", "value": "LAPTOP-KC6KER4Q"}, {"name": "thread", "value": "default-d009b7ee-b4ba-4887-8b98-8dfd59552afd"}, {"name": "tag", "value": "test_001"}]}